<div include-html="inc/fab.inc"></div>

<div class="row">
                <div class="col hide-on-med-and-down l2">

                    <!-- Sidebar Cards -->
                    <div include-html="inc/cards/pests.card"></div>
                    
                    <div include-html="inc/cards/piracy.card"></div>
                    
                    <div include-html="inc/cards/machine-learning.card"></div>
                    
                    <div include-html="inc/cards/future.card"></div>
                    
                </div>
        
                <div class="col s12 m9 l8">
                    <h1 class="blue-text text-darken-2">Entertainment Industry</h1>
                    <img src="images/entertainment.jpg" class="responsive-img">
                </div>
        
                <div class="col s12 m9 l8">
                    <div id="introduction" class="section scrollspy">
                        <h5>
                            While looking back at the past year, one thing becomes crystal clear: streaming has grown massively in 2017 and will continue to expand rapidly in 2018 and beyond. In fact, streaming has become the primary revenue driver for both music and video, thereby radically changing the way people consume content and profoundly altering the manner in which the industry and artists deliver media to fans.
                        </h5>
                        <p>
                            Digital television systems will offer programs that are sharper and clearer than current broadcast systems. The Internet — or some other high-speed communications network — will allow studios to send or "stream" hundreds of digital movies directly to digital theaters and homes. New "set-top boxes" and "digital hubs" in homes will automatically seek out programs and content that matches consumers' interest.
                        </p>
                        <p>
                            Yet digital technology is also raising thorny issues among Hollywood, technology companies, and consumers.
                        </p>
                    </div>

                    <div id="fair-use" class="section scrollspy">
                        <h3>Fair Use and Piracy</h3>
                        <p>
                            Chief concern among entertainment companies and consumers, for example, is the balance of copyright and so-called "fair-use." To prevent their digital programs from being perfectly copied and distributed by pirates, Hollywood studios want digital protection schemes in place. But technology companies say such measures would make it more difficult for legitimate consumers to enjoy the benefits of the technology.
                        </p>
                        <p>
                            Much as the music industry learned over the last few years, the technology used to create digital media can be used to illegally copy and "steal" the content. The record industry claims that millions of dollars were lost from pirates who "ripped" digital music from CDs using MP3 software technology and then share them others online through Web sites such as Napster.
                        </p>
                        <blockquote>
                            "Once content is available in downloaded and compressed form, it's easier to share — and harder to control," says Sean Wargo, senior industry analyst for the Consumer Electronics Association.
                        </blockquote>
                        <p>
                            Entertainment industry executives believe that technologies exist that could easily be implemented to protect their hard-developed content. So-called "watermarking" techniques, for example, would embed codes into the digital programs that would allow only legitimate users to access the programs on their digital receivers.

                            But consumer advocates question just what kind of "access" such technologies will allow.
                        </p>
                        <blockquote>
                            "Would you be able to take a copy [of a digital program] and loan it to a friend who missed [recording] it?" asks Fred von Lohmann, senior staff attorney for the Electronic Frontier Foundation. "There is a real danger that consumers will lose a lot of capabilities they are use to [now] and are fairly legitimate."
                        </blockquote>
                        <p>
                            Until the entertainment industry and the technology industry can work out how to safeguard digital content, it's unlikely that studios will actively pursue distributing movies on the Net soon.
                        </p>
                    </div>

                    <div id="time-and-cost" class="section scrollspy">
                        <h3>Time and Cost</h3>
                        <p>
                            Since most major motion pictures are edited using computer-based digital editing systems, studios and film-makers can save time by shooting directly onto digital video. Some directors are experimenting with shooting movies directly using digital video rather than traditional film stock. The next installment in George Lucas' Star Wars saga, for example, was shot in a digital format.
                        </p>
                        <p>
                            Ultimately, digital production may also save costs on distributing films to theaters. Instead of producing and shipping thousands of reels of films to theaters, studios could transfer the motion picture like any other computer file. Such film-less movies would save studios an estimated $600,000 in marketing costs for each major motion picture.
                        </p>
                        <blockquote>
                            "People will be able to create professional-level movies for an incredibly reasonable cost. You will see an explosion in the film-making process," Victor Harwood predicts.
                        </blockquote>
                    </div>

                    <div id="conclusion" class="section scrollspy">
                        <h3>Conclusion</h3>
                        <p>
                            Technology is driving the digital revolution while consumers increasingly embrace innovative solutions for their media consumption. Global smartphone ownership crossed the 2 billion mark in 2014 and it’s expected to reach an incredible 4.6 billion by 2019. Our world is now connected through the internet and social media in ways that exceed even the wildest imaginations of technology innovators from the past.
                        </p>
                        <p>
                            The growing access to a myriad of devices, such as smartphones, smart speakers, connected cars and connected homes, enables people to be online virtually anywhere and anytime, consuming music and television shows on-the-go. And it is this fundamental shift in consumer behavior and technological advancement that’s driving the rapid growth of music and video streaming, along with the rising importance of data and its ability to alter the creation and delivery of all media types.
                        </p>
                        <p>
                            The coming year will bring a multitude of new utilizations of technologies to the forefront. It’s expected that voice-controlled technology will take on a much larger role in the near future, following the success of Amazon’s Echo smart home device and the company’s Alexa personal assistant. Forthcoming innovations in voice tech hold the potential to radically alter the manner in which consumers search for and listen to music, resulting in an even bigger impact on revenue moving forward. Machine learning and artificial intelligence will increasingly penetrate the media industry, as the analytical sector develops innovative solutions to make data input actionable.
                        </p>
                        <p>
                            Perhaps most importantly, technology will continue to greatly improve the consumer experience. From enhancing discovery abilities to providing increasingly personalized and curated content delivery, the digital world holds the potential to entertain people in incredible ways that were once relegated to dreams.
                        </p>
                    </div>
                </div>

                <!-- Scrollspy -->
                <div class="col hide-on-small-only m3 l2">
                    <ul class="section table-of-contents pushpin">
                        <br><br><br><br><br>
                          <div include-html="inc/entertainment/contents.config"></div>
                    </ul>
                </div>
            </div>
            
            <!-- Footer -->
            <footer class="page-footer blue" style="z-index:800;">
                <div class="footer-copyright">
                    <div class="container" include-html="inc/entertainment/footer.config">
                    </div>
                </div>
            </footer>