<div class="background-image bg-further-info"></div>
<div class="row">
    <div class="col s12 m8 l6 center-text info-container further-info white show-on-medium-and-up">
            <h1 class="center-align black-text further-text">Further Information</h1>
            <h3 class="black-text further-text">Links:</h3>
            <ul>
                <li><a href="https://techfest.org/" target="_blank"><h4 style="font-weight:100;">&bull; Techfest</h4></a></li>
                <hr>
                <li><a href="https://doi.org/10.1038/544S21a" target="_blank"><h4 style="font-weight:100;">&bull; Agriculture - <i>"Technology: The Future of Agriculture"</i></h4></a></li>
                <li><a href="https://apiumhub.com/tech-blog-barcelona/future-technology-education/" target="_blank"><h4 style="font-weight:100;">&bull; Education - <i>"Future of Technology in Education"</i></h4></a></li>
                <li><a href="https://abcnews.go.com/Technology/story?id=98049" target="_blank"><h4 style="font-weight:100;">&bull; Entertainment - <i>The Tricky Future of Digital Home Entertainment"</i></h4></a></li>
                <li><a href="https://medium.com/the-mission/technology-to-shape-the-future-of-media-entertainment-a1e3acd3b3ac" target="_blank"><h4 style="font-weight:100;">&bull; Entertainment - <i>"Technology to Shape the Future of Media &amp; Entertainment"</i></h4></a></li>
                <li><a href="https://www.expansionsolutionsmagazine.com/111217_healthcare" target="_blank"><h4 style="font-weight:100;">&bull; Medical - <i>"Digital Tech Trends and the Future of the Health Care Industry"</i></h4></a></li>
                <li></li>
                <li></li>
            </ul>
    </div>
    <div class="col s12 further-info white hide-on-med-and-up">
            <h1 class="center-align black-text further-text">Further Information</h1>
            <h3 class="black-text further-text">Links:</h3>
            <ul>
                <li><a href="https://techfest.org/" target="_blank"><h4 style="font-weight:100;">&bull; Techfest</h4></a></li>
                <hr>
                <li><a href="https://doi.org/10.1038/544S21a" target="_blank"><h4 style="font-weight:100;">&bull; Agriculture - <i>"Technology: The Future of Agriculture"</i></h4></a></li>
                <li><a href="https://apiumhub.com/tech-blog-barcelona/future-technology-education/" target="_blank"><h4 style="font-weight:100;">&bull; Education - <i>"Future of Technology in Education"</i></h4></a></li>
                <li><a href="https://abcnews.go.com/Technology/story?id=98049" target="_blank"><h4 style="font-weight:100;">&bull; Entertainment - <i>The Tricky Future of Digital Home Entertainment"</i></h4></a></li>
                <li><a href="https://medium.com/the-mission/technology-to-shape-the-future-of-media-entertainment-a1e3acd3b3ac" target="_blank"><h4 style="font-weight:100;">&bull; Entertainment - <i>"Technology to Shape the Future of Media &amp; Entertainment"</i></h4></a></li>
                <li><a href="https://www.expansionsolutionsmagazine.com/111217_healthcare" target="_blank"><h4 style="font-weight:100;">&bull; Medical - <i>"Digital Tech Trends and the Future of the Health Care Industry"</i></h4></a></li>
                <li></li>
                <li></li>
            </ul>
    </div>
</div>