<div class="background-image bg-home"></div>
<div class="row valign-wrapper">
    <div class="col s12 center-text">
            <h3 class="center-align white-text">Welcome to DTFuture</h3>
            <h5 class="center-align white-text">An informative website on the future of Digital Technologies in different industries, created for Techfest Porirua 2018.</h5>
            <h5 class="center-align white-text"><strong>Click on a link in the navigation bar to get started.</strong></h5>
    </div>
</div>