<div class="background-image bg-home" data-slides='["images/technology.jpg","images/agricultural.jpg","images/education.jpg","images/entertainment.jpg","images/medical.jpg"]'></div>
<div class="row valign-wrapper">
    <div class="col s12 center-text">
            <h4 class="center-align white-text">Welcome to DTFuture</h4>
            <h5 class="center-align white-text">Click on a link in the navigation bar to get started.</h5>
    </div>
</div>